language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - npm run -D
  - cd ./test/smoke/template
  - npm install -D

script:
  - npm run test